version: '3.8'

services:
  # FastAPI backend service
  backend:
    image: shayoossi/farm-backend:20
      
      
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  # React frontend service
   

  frontend:
    image: shayoossi/farm-frontend:20
    ports:
      - "3000:80"
    depends_on:
      - backend

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
